/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as DevicesIndexImport } from './routes/devices/index'
import { Route as DevicesSmsChatDeviceIdImport } from './routes/devices/smsChat.$deviceId'
import { Route as DevicesSmsDeviceIdImport } from './routes/devices/sms.$deviceId'
import { Route as DevicesFilesDeviceIdImport } from './routes/devices/files.$deviceId'
import { Route as DevicesContactsDeviceIdImport } from './routes/devices/contacts.$deviceId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DevicesIndexRoute = DevicesIndexImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRoute,
} as any)

const DevicesSmsChatDeviceIdRoute = DevicesSmsChatDeviceIdImport.update({
  id: '/devices/smsChat/$deviceId',
  path: '/devices/smsChat/$deviceId',
  getParentRoute: () => rootRoute,
} as any)

const DevicesSmsDeviceIdRoute = DevicesSmsDeviceIdImport.update({
  id: '/devices/sms/$deviceId',
  path: '/devices/sms/$deviceId',
  getParentRoute: () => rootRoute,
} as any)

const DevicesFilesDeviceIdRoute = DevicesFilesDeviceIdImport.update({
  id: '/devices/files/$deviceId',
  path: '/devices/files/$deviceId',
  getParentRoute: () => rootRoute,
} as any)

const DevicesContactsDeviceIdRoute = DevicesContactsDeviceIdImport.update({
  id: '/devices/contacts/$deviceId',
  path: '/devices/contacts/$deviceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/devices/contacts/$deviceId': {
      id: '/devices/contacts/$deviceId'
      path: '/devices/contacts/$deviceId'
      fullPath: '/devices/contacts/$deviceId'
      preLoaderRoute: typeof DevicesContactsDeviceIdImport
      parentRoute: typeof rootRoute
    }
    '/devices/files/$deviceId': {
      id: '/devices/files/$deviceId'
      path: '/devices/files/$deviceId'
      fullPath: '/devices/files/$deviceId'
      preLoaderRoute: typeof DevicesFilesDeviceIdImport
      parentRoute: typeof rootRoute
    }
    '/devices/sms/$deviceId': {
      id: '/devices/sms/$deviceId'
      path: '/devices/sms/$deviceId'
      fullPath: '/devices/sms/$deviceId'
      preLoaderRoute: typeof DevicesSmsDeviceIdImport
      parentRoute: typeof rootRoute
    }
    '/devices/smsChat/$deviceId': {
      id: '/devices/smsChat/$deviceId'
      path: '/devices/smsChat/$deviceId'
      fullPath: '/devices/smsChat/$deviceId'
      preLoaderRoute: typeof DevicesSmsChatDeviceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices': typeof DevicesIndexRoute
  '/devices/contacts/$deviceId': typeof DevicesContactsDeviceIdRoute
  '/devices/files/$deviceId': typeof DevicesFilesDeviceIdRoute
  '/devices/sms/$deviceId': typeof DevicesSmsDeviceIdRoute
  '/devices/smsChat/$deviceId': typeof DevicesSmsChatDeviceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices': typeof DevicesIndexRoute
  '/devices/contacts/$deviceId': typeof DevicesContactsDeviceIdRoute
  '/devices/files/$deviceId': typeof DevicesFilesDeviceIdRoute
  '/devices/sms/$deviceId': typeof DevicesSmsDeviceIdRoute
  '/devices/smsChat/$deviceId': typeof DevicesSmsChatDeviceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/contacts/$deviceId': typeof DevicesContactsDeviceIdRoute
  '/devices/files/$deviceId': typeof DevicesFilesDeviceIdRoute
  '/devices/sms/$deviceId': typeof DevicesSmsDeviceIdRoute
  '/devices/smsChat/$deviceId': typeof DevicesSmsChatDeviceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/devices'
    | '/devices/contacts/$deviceId'
    | '/devices/files/$deviceId'
    | '/devices/sms/$deviceId'
    | '/devices/smsChat/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/devices'
    | '/devices/contacts/$deviceId'
    | '/devices/files/$deviceId'
    | '/devices/sms/$deviceId'
    | '/devices/smsChat/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/devices/'
    | '/devices/contacts/$deviceId'
    | '/devices/files/$deviceId'
    | '/devices/sms/$deviceId'
    | '/devices/smsChat/$deviceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
  DevicesContactsDeviceIdRoute: typeof DevicesContactsDeviceIdRoute
  DevicesFilesDeviceIdRoute: typeof DevicesFilesDeviceIdRoute
  DevicesSmsDeviceIdRoute: typeof DevicesSmsDeviceIdRoute
  DevicesSmsChatDeviceIdRoute: typeof DevicesSmsChatDeviceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  DevicesContactsDeviceIdRoute: DevicesContactsDeviceIdRoute,
  DevicesFilesDeviceIdRoute: DevicesFilesDeviceIdRoute,
  DevicesSmsDeviceIdRoute: DevicesSmsDeviceIdRoute,
  DevicesSmsChatDeviceIdRoute: DevicesSmsChatDeviceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/devices/",
        "/devices/contacts/$deviceId",
        "/devices/files/$deviceId",
        "/devices/sms/$deviceId",
        "/devices/smsChat/$deviceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/devices/": {
      "filePath": "devices/index.tsx"
    },
    "/devices/contacts/$deviceId": {
      "filePath": "devices/contacts.$deviceId.tsx"
    },
    "/devices/files/$deviceId": {
      "filePath": "devices/files.$deviceId.tsx"
    },
    "/devices/sms/$deviceId": {
      "filePath": "devices/sms.$deviceId.tsx"
    },
    "/devices/smsChat/$deviceId": {
      "filePath": "devices/smsChat.$deviceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
